### ISSUE TITLE
Decouple CLISOPS and Xclim?

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim-feedstock#1]
@Ouranosinc/xclim-core 

With regridding and bias correction capabilities, CLISOPS has become a lot more than just a subsetting library. Additionally, some of its dependencies are not playing nicely for some projects (specifically RavenPy and RavenWPS). I am wondering if we could easily unbundle it from the conda-forge package and just explicitly install it in the services that need it. 

See: 
- https://github.com/CSHS-CWRA/RavenPy/pull/120
- https://github.com/CSHS-CWRA/RavenPy/pull/121
- https://github.com/Ouranosinc/raven/pull/397#issuecomment-884494724

**Comment by aulemahal** [comment]
I agree! I don't think the userbase of xclim is large enough to justify all this dependency complexity we impose on ourselves with keeping `xclim.subset`.

**Comment by Zeitsperre** [comment]
Closed by https://github.com/conda-forge/xclim-feedstock/pull/42
